# Site Info
title: Han Trung Kien
tagline: Life is sharing. You will never walk alone!
description: 'Life is sharing. You will never walk alone!'
baseurl: ""
url:
logo: '/images/jboy-papyrus-blue.png'

# Site configurations
gems:
  - jekyll-paginate  
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji # GitHub-flavored Emoji plugin for Jekyll
markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

excerpt_separator: <!--more-->
sass:
  style: compressed
  sass_dir: _scss
paginate: 10
paginate_path: '/blog/page:num'
permalink: /:year/:month/:day/:title/

timezone: UTC

version: 1.0.0

# About/contact
author:
  name: Han Trung Kien
  description: A passionate Android <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 4d55c9f8de95c0d8061d36428e8f7be9 # md5 hash of your email address
  contact:
    # linkedin:  
    github:    https://github.com/hantrungkien
    # facebook:  
    # twitter:   
    # google-plus: 
    # weibo:     http://weibo.com/41173780
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
    - { Archive: '/blog/archive/' }
  About:
    - '/about/'
  # Github Project: 
    # - 'http://codinfox.github.io/'
  Good Stuffs:
    - '/good-stuffs/'
  Free Books:
    - '/free-books/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-112039340-2' # leave blank if you don't want google analytics
disqus_short_name: 'hantrungkien' # leave blank if you don't want disqus

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
